version: '{branch}-{build}'

image:
  - Visual Studio 2013
  - Visual Studio 2017

# called before clone
init:
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" (set GENERATOR="Visual Studio 15 2017 Win64" && set SGEN=vs2017-x64)
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" (set GENERATOR="Visual Studio 14 2015 Win64" && set SGEN=vs2015-x64)
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" (set GENERATOR="Visual Studio 12 2013 Win64" && set SGEN=vs2013-x64)
  - echo %GENERATOR%
  - echo %Configuration%
  - if "%Configuration%"=="Debug"   (set config=debug)
  - if "%Configuration%"=="Release" (set config=release)
  - set BUILD_TOOLS=OFF
  - FOR /F "tokens=3 delims= " %%i in ('echo %APPVEYOR_BUILD_WORKER_IMAGE%') do set YEAR=%%i
  - echo %YEAR%

# doesn't seem to be able to use environmental vars
clone_folder: C:\iricdev\lib\src\iriclib

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

# Note mkdir is from Git (C:\Program Files\Git\usr\bin\mkdir.exe)
# It might give unexpected results (use md instead)
#
# Qt 5.5 only supports VS2013
before_build:
  - REM call C:\Qt\5.5\msvc2013_64\bin\qtenv2.bat
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86_amd64
  - cd C:\iricdev
  - curl -L -O https://github.com/i-RIC/iricdev/archive/master.zip
  - 7z e master.zip
  - rd iricdev-master
  - del master.zip
  - unix2dos *
  - copy appveyor_programs.prop programs.prop
  - call versions.cmd
  - msbuild /nologo /target:cgnslib-build-%config% iricdev.proj
  - if "%CGNSLIB_VER%"=="3.2.1" (set CGNSLIB_VER=%CGNSLIB_VER%-patch1)

# build using cmake tools
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir _build
  - cd _build
  - set CMAKE_PREFIX_PATH=c:\iricdev\lib\install\hdf5-%HDF5_VER%\%config%\cmake\hdf5;c:\iricdev\lib\install\cgnslib-%CGNSLIB_VER%\%config%
  - cmake -G %GENERATOR% -DCMAKE_INSTALL_PREFIX:PATH=%CD%/INSTALL ..
  - msbuild iriclib.sln /p:Configuration=%Configuration%

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\_build
  - set path=c:\iricdev\lib\install\hdf5-%HDF5_VER%\%config%\bin;c:\iricdev\lib\install\cgnslib-%CGNSLIB_VER%\%config%\bin;%PATH%
  - ctest -C %Configuration%

after_test:
  - cd %APPVEYOR_BUILD_FOLDER%\_build
  - msbuild INSTALL.vcxproj /p:Configuration=%Configuration%

# must be relative to APPVEYOR_BUILD_FOLDER
artifacts:
  - path: _build\INSTALL

# ??? doesn't seem to be able to use environmental vars ???
#  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
cache:
  - C:\iricdev\lib\install
